apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-values
  namespace: myapp
data:
  values.yaml: |
    image:
      repository: ghcr.io/jasongladhill13/fastapiapp
      tag: "initial"
    service:
      port: 80